### ISSUE TITLE
Meeting Minutes 2023-01-16

### ISSUE THREAD

**Issue by srfrew** [UBC-MDS/eda_mds#17]
Meeting Minutes for 2023-01-16:
- Completed paired programming exercise to scaffold tests for each function
- Discussed use of `conftest.py` for standardizing test data. Opted to not implement due to different function needs
- Discussed `poetry` implementation and addition of requirements
    - ~~to be updated after individual work is completed to minimize fragmentation (follow up)~~
- Split work and updated project boards

**Comment by srfrew** [comment]
Update for all after discussing with Tiff about poetry and dependencies.
1. We **should** be updating `poetry` as we work on our individual branches. 
2. It may be best practice to create a conda environment with the project python version and poetry, then let poetry handle dependencies. 
    - This is for new developers to may join, protect our personal conda installations from poetry, and to ensure that all dependencies are added and managed by poetry for the specific project

@korayt @nicolebid @paolocodina

**Comment by nicolebid** [comment]
Got it, thanks!
