### ISSUE TITLE
Meeting Minutes 2024/1/9

### ISSUE THREAD

**Issue by nicolebid** [UBC-MDS/eda_mds#3]
Summary
- completed contract (meeting time, roles discussed, etc.--see contract for details) 
- topic selected: EDA
- discussed functions & assigned to team members

Action Items: 
- complete individual function specifications (.py file)
- complete project structure task

Next Meeting: Thursday, Jan 11, before lab

**Comment by srfrew** [comment]
These look great! Tasks are completed and Milestone 1 is nearly finished.
