### ISSUE TITLE
Package Documentation with Sphinx

### ISSUE THREAD

**Issue by srfrew** [UBC-MDS/eda_mds#40]

**Comment by srfrew** [comment]
I believe we need to review our `py_counts` example for integrating sphinx

**Comment by nicolebid** [comment]
Here's the commands:

$ poetry add --group dev myst-nb --python "^3.9"
$ poetry add --group dev sphinx-autoapi sphinx-rtd-theme

**Comment by korayt** [comment]
created the online version for our documentation https://eda-mds.readthedocs.io/en/latest/?badge=latest

**Comment by korayt** [comment]
> Here's the commands:
> 
> $ poetry add --group dev myst-nb --python "^3.9" $ poetry add --group dev sphinx-autoapi sphinx-rtd-theme

updated the environment and poetry files as well
