### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by nicolebid** [UBC-MDS/eda_mds#50]
Any thoughts on a suitable license can be discussed here.

**Comment by nicolebid** [comment]
pandas uses the BSD 3-Clause License:  https://github.com/pandas-dev/pandas/blob/main/LICENSE 
I think either using the same license or the MIT license could be suitable here. 

Thoughts?

**Comment by korayt** [comment]
MIT is one of the most permissive licenses out there. It could be good to have MIT so that people are encouraged to experiment and develop with our package.

**Comment by paolocodina** [comment]
I understand it is also the most common to use.

**Comment by srfrew** [comment]
I agree with the MIT license approach and think it makes sense for a simple yet useful package. 
We may need to make it clear that pandas and numpy are covered under another license, although we are not copying source code in any way.

**Comment by srfrew** [comment]
I'm going to look into a CC license for the written work, like the vignette. If folks aren't opposed, I'll go with a public domain or non-commercial use CC license.

**Comment by nicolebid** [comment]
Sounds great, thanks!
